### ISSUE TITLE
The validation message doesn't come up in release mode.

### ISSUE THREAD

**Issue by santoshg31** [kiliman/mvx-samples#1]
This works perfectly fine in Debug mode  for android but doesn't work in Release mode.
Is there something needs to be added in LinkerPleaseinclude.cs file ?

Also is it possible to do the same in Xamarin.ios with Storyboards ?

**Comment by JosephDevlin** [comment]
Having exact same issue. The validation in the sample app itself is broken in release mode.

**Comment by kiliman** [comment]
@santoshg31 sorry for the late reply. The email notification must have gotten buried.

Anyway, not sure why it's not working for you. Although I haven't really touched this code in a while. Try adding the following to LinkerPleaseInclude.cs (*I didn't need it in mine, but perhaps a newer version of MvvmCross changed things*):

```c#
        public void Include(EditText text)
        {
            text.Error = "" + text.Error;
        }
```

NOTE: We ended up not using MvvmCross for our iOS apps, instead going with Swift, so not sure how to do the equivalent for iOS. Sorry.

**Comment by JosephDevlin** [comment]
Hi, I downloaded and got the issue working in your sample. I was going to see about putting a PR into your repo some time tomorrow but I could just give you the code changes to make it work if you want to make the commit yourself. The following makes the validation work in release mode.

```c#
        public void Include(EditText text)
        {
            text.AfterTextChanged += (sender, args) => text.Text = "" + text.Text;
            text.Hint = "" + text.Hint;
            text.Error = "" + text.Error;
        }
```

**Comment by kiliman** [comment]
Awesome. Glad you were able to figure it out.
